version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'dbapi'   
      MYSQL_USER: 'api_user'
      MYSQL_PASSWORD: 'api_pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - "./db.sql:/docker-entrypoint-initdb.d/1.sql"

  api-01:
    build: .
    volumes:
      - ./app/:/app
    networks:
      - proxy

  api-02:
    build: .
    volumes:
      - ./app/:/app
    networks:
      - proxy
